# Generated by Django 4.2.7 on 2023-11-21 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={"ordering": ["-value"], "verbose_name_plural": "ratings"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name_plural": "students",
            },
        ),
        migrations.AlterModelTable(
            name="rating",
            table="ratings",
        ),
        migrations.AlterModelTable(
            name="student",
            table="students",
        ),
    ]
