# Generated by Django 4.2.7 on 2023-11-29 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_remove_student_value_rating_student"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={},
        ),
        migrations.AlterField(
            model_name="rating",
            name="student",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="myapp.student",
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.FloatField(verbose_name="Rating Value"),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(
                help_text="Enter student's first name",
                max_length=100,
                verbose_name="First Name",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(
                help_text="Enter student's last name",
                max_length=100,
                verbose_name="Last Name",
            ),
        ),
        migrations.AlterModelTable(
            name="rating",
            table=None,
        ),
        migrations.AlterModelTable(
            name="student",
            table=None,
        ),
    ]
